### ISSUE TITLE
ModuleNotFoundError: No module named 'onnxruntime'

### ISSUE THREAD

**Issue by douagz** [facefusion/facefusion-docker#11]
There's an error, ModuleNotFoundError: No module named 'onnxruntime' , when 'docker-compose -f docker-compose.cpu.yml up' is executed.

C:\Users\admin\Documents\...\facefusion-docker>**docker-compose -f docker-compose.cpu.yml up**
[+] Building 4.5s (12/12) FINISHED                                                                       docker:default
 => [facefusion-cpu internal] load build definition from Dockerfile.cpu                                            0.0s
 => => transferring dockerfile: 398B                                                                               0.0s
 => [facefusion-cpu internal] load .dockerignore                                                                   0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [facefusion-cpu internal] load metadata for docker.io/library/python:3.10                                      4.4s
 => [facefusion-cpu auth] library/python:pull token for registry-1.docker.io                                       0.0s
 => [facefusion-cpu 1/7] FROM docker.io/library/python:3.10@sha256:eac7369136625549bc3f7461fe072b1030f538ea20d629  0.0s
 => CACHED [facefusion-cpu 2/7] WORKDIR /facefusion                                                                0.0s
 => CACHED [facefusion-cpu 3/7] RUN apt-get update                                                                 0.0s
 => CACHED [facefusion-cpu 4/7] RUN apt-get install curl -y                                                        0.0s
 => CACHED [facefusion-cpu 5/7] RUN apt-get install ffmpeg -y                                                      0.0s
 => CACHED [facefusion-cpu 6/7] RUN git clone https://github.com/facefusion/facefusion.git --branch 1.3.1 --singl  0.0s
 => CACHED [facefusion-cpu 7/7] RUN python install.py --torch cpu --onnxruntime default                            0.0s
 => [facefusion-cpu] exporting to image                                                                            0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:09fc17e82a45f9683f18b76e76b5515a7869082a128a4661b7052b5e62ce8ce3                       0.0s
 => => naming to docker.io/library/facefusion-docker-facefusion-cpu                                                0.0s
[+] Running 2/2
 ✔ Network facefusion-docker_default             Created                                                           0.0s
 ✔ Container facefusion-docker-facefusion-cpu-1  Created                                                           4.1s
Attaching to facefusion-docker-facefusion-cpu-1
facefusion-docker-facefusion-cpu-1  | Traceback (most recent call last):
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/run.py", line 3, in <module>
facefusion-docker-facefusion-cpu-1  |     from facefusion import core
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/facefusion/core.py", line 11, in <module>
facefusion-docker-facefusion-cpu-1  |     import onnxruntime
facefusion-docker-facefusion-cpu-1  | **ModuleNotFoundError: No module named 'onnxruntime'**
facefusion-docker-facefusion-cpu-1 exited with code 1

**Comment by henryruhs** [comment]
Sorry, but I cannot reproduce this.

**Comment by sinhpn92** [comment]
I have the same issue.

Environment:
- OS: Mac OS Apple Silicon M1
- Docker: Docker version 24.0.6

Steps to reproduce:
- Clone repository from this repo.
- Run from the terminal: `docker compose -f docker-compose.cpu.yml up -d`
