### ISSUE TITLE
Missing pip install in dockerfile.cpu

### ISSUE THREAD

**Issue by kirby0025** [facefusion/facefusion-docker#13]
Hello,

In the Dockerfile.cpu, you are missing the "RUN apt-get install python3-pip -y" command.
```
RUN apt-get update
RUN apt-get install curl -y
RUN apt-get install ffmpeg -y
RUN apt-get install python3-pip -y
```

**Comment by henryruhs** [comment]
Not needed... take a look into the CI pipeline before opening issues
