### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by hakimilg** [facefusion/facefusion-docker#18]
When I run `docker-compose -f docker-compose.cpu.yml up` from a newly cloned repo, I get the following error
```sh
[+] Running 1/0
 ✔ Container facefusion-docker-facefusion-cpu-1  Created                                                                                                               0.0s 
Attaching to facefusion-docker-facefusion-cpu-1
facefusion-docker-facefusion-cpu-1  | Traceback (most recent call last):
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/run.py", line 3, in <module>
facefusion-docker-facefusion-cpu-1  |     from facefusion import core
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/facefusion/core.py", line 16, in <module>
facefusion-docker-facefusion-cpu-1  |     from facefusion.face_analyser import get_one_face, get_average_face
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/facefusion/face_analyser.py", line 3, in <module>
facefusion-docker-facefusion-cpu-1  |     import cv2
facefusion-docker-facefusion-cpu-1  | ModuleNotFoundError: No module named 'cv2'
facefusion-docker-facefusion-cpu-1 exited with code 1
```

What do I do wrong?

**Comment by henryruhs** [comment]
Similar to https://github.com/facefusion/facefusion-docker/issues/11 ... platform issue I guess

**Comment by hakimilg** [comment]
I should have added that I used to have an older version (`1.3.1`) that worked. I wanted to upgrade, and got the error.
So I stopped and deleted all containers, and removed all images.
Maybe I left some pieces of data somewhere? In volumes?

**Comment by henryruhs** [comment]
It's possible that you are using outdated Docker layers... yes

**Comment by hakimilg** [comment]
I'll try to upgrade my docker and docker compose

**Comment by henryruhs** [comment]
It can be tricky to invalidate the layers... I suggest you rename the Dockerfile and point to that new file in the docker compose yml.

Join our Discord for more help.
