### ISSUE TITLE
docker cpu up error with ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by heiansl** [facefusion/facefusion-docker#19]
[+] Running 1/0ion-docker>docker-compose -f docker-compose.cpu.yml up
 ✔ Container facefusion-docker-facefusion-cpu-1  Created                                                                                                               0.0s
Attaching to facefusion-docker-facefusion-cpu-1
facefusion-docker-facefusion-cpu-1  | Traceback (most recent call last):
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/run.py", line 3, in <module>
facefusion-docker-facefusion-cpu-1  |     from facefusion import core
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/facefusion/core.py", line 16, in <module>
facefusion-docker-facefusion-cpu-1  |     from facefusion.face_analyser import get_one_face, get_average_face
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/facefusion/face_analyser.py", line 3, in <module>
facefusion-docker-facefusion-cpu-1  |     import cv2
facefusion-docker-facefusion-cpu-1  | ModuleNotFoundError: No module named 'cv2'
facefusion-docker-facefusion-cpu-1 exited with code 1

**Comment by henryruhs** [comment]
This happens when you mix new and outdated container layers.

**Comment by heiansl** [comment]
Find, i have resolved it by `docker-compose -f docker-compose.cpu.yml build --no-cache` and configure a proxy and add `
RUN git config --global http.version HTTP/1.1` in Dockerfile.cpu.

**Comment by heiansl** [comment]
And now， there are new problem.
![image](https://github.com/facefusion/facefusion-docker/assets/31236821/ff6be59c-147c-4910-90c3-0496b6f9984b)

**Comment by xiaohange** [comment]
GPU

```shell
[+] Running 1/0
 ⠿ Container facefusion-docker-facefusion-cuda-1  Created                                                                           0.0s
Attaching to facefusion-docker-facefusion-cuda-1
facefusion-docker-facefusion-cuda-1  | 
facefusion-docker-facefusion-cuda-1  | ==========
facefusion-docker-facefusion-cuda-1  | == CUDA ==
facefusion-docker-facefusion-cuda-1  | ==========
facefusion-docker-facefusion-cuda-1  | 
facefusion-docker-facefusion-cuda-1  | CUDA Version 11.8.0
facefusion-docker-facefusion-cuda-1  | 
facefusion-docker-facefusion-cuda-1  | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
facefusion-docker-facefusion-cuda-1  | 
facefusion-docker-facefusion-cuda-1  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
facefusion-docker-facefusion-cuda-1  | By pulling and using the container, you accept the terms and conditions of this license:
facefusion-docker-facefusion-cuda-1  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
facefusion-docker-facefusion-cuda-1  | 
facefusion-docker-facefusion-cuda-1  | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
facefusion-docker-facefusion-cuda-1  | 
facefusion-docker-facefusion-cuda-1  | Traceback (most recent call last):
facefusion-docker-facefusion-cuda-1  |   File "/facefusion/run.py", line 3, in <module>
facefusion-docker-facefusion-cuda-1  |     from facefusion import core
facefusion-docker-facefusion-cuda-1  |   File "/facefusion/facefusion/core.py", line 16, in <module>
facefusion-docker-facefusion-cuda-1  |     from facefusion.face_analyser import get_one_face, get_average_face
facefusion-docker-facefusion-cuda-1  |   File "/facefusion/facefusion/face_analyser.py", line 4, in <module>
facefusion-docker-facefusion-cuda-1  |     import cv2
facefusion-docker-facefusion-cuda-1  | ModuleNotFoundError: No module named 'cv2'
facefusion-docker-facefusion-cuda-1 exited with code 1
```
