### ISSUE TITLE
There are seem all model are not found.

### ISSUE THREAD

**Issue by heiansl** [facefusion/facefusion-docker#20]
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/facefusion/face_analyser.py", line 116, in detect_with_retinaface
facefusion-docker-facefusion-cpu-1  |     face_detector = get_face_analyser().get('face_detector')
facefusion-docker-facefusion-cpu-1  |   File "/facefusion/facefusion/face_analyser.py", line 59, in get_face_analyser
facefusion-docker-facefusion-cpu-1  |     face_detector = onnxruntime.InferenceSession(MODELS.get('face_detector_retinaface').get('path'), providers = facefusion.globals.execution_providers)
facefusion-docker-facefusion-cpu-1  |   File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
facefusion-docker-facefusion-cpu-1  |     self._create_inference_session(providers, provider_options, disabled_optimizers)
facefusion-docker-facefusion-cpu-1  |   File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
facefusion-docker-facefusion-cpu-1  |     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
facefusion-docker-facefusion-cpu-1  | onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /facefusion/.assets/models/retinaface_10g.onnx failed:Load model /facefusion/.assets/models/retinaface_10g.onnx failed. File doesn't exist

**Comment by heiansl** [comment]
![image](https://github.com/facefusion/facefusion-docker/assets/31236821/ac2f2689-aff3-4540-85be-b3622d25ed1d)

**Comment by henryruhs** [comment]
Permission issue on your side.
