### ISSUE TITLE
Command syntaxt not correct

### ISSUE THREAD

**Issue by idakir** [facefusion/facefusion-docker#21]
The correct command should be like below, without hifen "-":
docker compose -f docker-compose.cpu.yml up

**Comment by henryruhs** [comment]
Depends on the version being used...

**Comment by idakir** [comment]
It’s not related to the version, the docker-compose command doesn’t exist, you can check the docker link page
https://docs.docker.com/engine/reference/commandline/compose/

**Comment by henryruhs** [comment]
Don't try to teach me... the one thing is the old standalone docker-compose. What you are using is the new compose plugin for docker.
