### ISSUE TITLE
docker-compose cuda error.

### ISSUE THREAD

**Issue by emtc** [facefusion/facefusion-docker#26]
=> ERROR [12/12] RUN cd /usr/local/lib/python3.10/dist-packages/torch/lib && ln -s libnvrtc-672ee683.so.11.2 libnvrtc.so                                                                 0.1s
------
 > [12/12] RUN cd /usr/local/lib/python3.10/dist-packages/torch/lib && ln -s libnvrtc-672ee683.so.11.2 libnvrtc.so:
0.116 /bin/sh: 1: cd: can't cd to /usr/local/lib/python3.10/dist-packages/torch/lib
------
Dockerfile.cuda:19
--------------------
  17 |     RUN python install.py --torch cuda-11.8 --onnxruntime cuda-11.8 --skip-venv
  18 |
  19 | >>> RUN cd /usr/local/lib/python3.10/dist-packages/torch/lib && ln -s libnvrtc-672ee683.so.11.2 libnvrtc.so
  20 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /usr/local/lib/python3.10/dist-packages/torch/lib && ln -s libnvrtc-672ee683.so.11.2 libnvrtc.so" did not complete successfully: exit code: 2
ERROR: Service 'facefusion-cuda' failed to build : Build failed
root@iZbp1g6u4mfoqizw32yg4wZ:~/facefusion-docker# docker-compose -f docker-compose.cuda.yml up

**Comment by henryruhs** [comment]
Yeah, seeing this now in our CI as well - the base container must have been updated.
