### ISSUE TITLE
response from daemon: could not select device driver "rocm" with capabilities: [[gpu video]]

### ISSUE THREAD

**Issue by dagedan** [facefusion/facefusion-docker#29]
`:/facefusion-docker$ **docker compose -f docker-compose.rocm.yml up -d**
WARN[0000] Found orphan containers ([facefusion-docker-facefusion-cuda-1 facefusion-docker-facefusion-cpu-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 0/1
 ⠹ Container facefusion-docker-facefusion-rocm-1  Starting                                                                                                                                               0.2s 
Error response from daemon: could not select device driver "rocm" with capabilities: [[gpu video]]
`
Fri Apr 19 17:19:18 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.67                 Driver Version: 550.67         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060 ...    Off |   00000000:42:00.0 Off |                  N/A |
| 41%   36C    P8              4W /  175W |     591MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A    379810      C   python                                        588MiB |
+-----------------------------------------------------------------------------------------+

**Comment by henryruhs** [comment]
Using ROCM (for AMD) with a NIVIDA card? Do not open issues like that if you don't know what you are doing.
