### ISSUE TITLE
Docker + CUDA

### ISSUE THREAD

**Issue by kristiankielhofner** [facefusion/facefusion-docker#3]
I almost exclusively use CUDA with docker. On my dev workstation when using this repo CUDA isn't utilized even though it is detected as the execution provider:

`Processing: 100%|██████████| 197/197 [01:04<00:00,  3.05frame/s, memory_usage=06.71GB, execution_providers=['CUDAExecutionProvider'], execution_thread_count=8, execution_queue_count=1]`

When checking GPU status with `nvidia-smi` I never see the model loaded to memory or executing there. nvenc doesn't appear to work either.

I hacked up my own variant with a Dockerfile FROM `nvcr.io/nvidia/tensorflow:23.08-tf2-py3` and I'm able to see the model load in VRAM but it still doesn't execute there. In my variant I'm also able to use nvenc and verify via `nvidia-smi` that is in actually being utilized.

Hardware is Nvidia RTX 4090.

Any thoughts? How can I help?

**Comment by henryruhs** [comment]
Please join our Discord server and join the #cloud channel under troubleshooting.

**Comment by min-star** [comment]
me too

**Comment by henryruhs** [comment]
I'm honestly not able to work on this as Docker troubleshooting takes a lot of time.

A member of the community has to take over.

**Comment by skerdibash** [comment]
Could this be causing the problem https://github.com/microsoft/onnxruntime/discussions/7387?

**Comment by JxiaoC** [comment]
me too

**Comment by henryruhs** [comment]
Spend a couple of hours, no luck. When you take a look to the official [Dockerfile.cuda](https://github.com/microsoft/onnxruntime/blob/main/dockerfiles/Dockerfile.cuda) you will figure out that the `nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04` is used for compiling only and `nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04` to run like we do.

**Comment by skerdibash** [comment]
I also did some testing lately and I don't know if this is related to a problem with my docker setup/usage, but I noticed that during the image building using the cuda Dockerfile, the cuda base image is not used, resulting in an image compromising only of the python base image and the instructions that follow it. The docker documentation seems to suggest that this is the expected behavior when using multiple FROM statements.

**Comment by henryruhs** [comment]
I think it is used, but the `RUN` commands are applied to the latest `FROM` image only.

**Comment by skerdibash** [comment]
Yes the way I am doing it right now, is by using a cuda image as base and installing python through apt. I built two images(using devel and runtime) and verified that a cuda containing base image was used for both, by connecting to the docker container with docker exec. 

I currently don't have access to a cuda enabled gpu, but I will be able to test it tomorrow on one. Hopefully it works.

**Comment by henryruhs** [comment]
Drop the file here... someone gonna test it.

**Comment by skerdibash** [comment]
So this is the latest dockerfile I am experimenting with, it  finally creates an image using the runtime version of the cuda base image: https://gist.github.com/skerdibash/dab2c033eb76f5cdce8bec30a6d65dde

I still used a multistage build but only for creating an cuda/nvenc enabled ffmpeg and copying it in the final image, cuda devel is used in the first stage and cuda runtime in the second/final stage.

For the cuda/nvenc enabled ffmpeg I used instructions from:
- https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html
- https://pytorch.org/audio/master/build.ffmpeg.html

**Comment by henryruhs** [comment]
Your gist does not work... same issue like I had:

```
#0 13.81 Setting up python3.10-minimal (3.10.12-1~22.04.2) ...
#0 13.86 [Errno 13] Permission denied: '/usr/lib/python3.10/__pycache__/__future__.cpython-310.pyc.140307446897264'dpkg: error processing package python3.10-minimal (--configure):
#0 13.86  installed python3.10-minimal package post-installation script subprocess returned error exit status 1
#0 13.86 Errors were encountered while processing:
#0 13.86  python3.10-minimal
#0 13.87 E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by min-star** [comment]
> I think it is used, but the `RUN` commands are applied to the latest `FROM` image only.
> 
> ```
> FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04 as base
> 
> COPY --from=base /usr/local/cuda /usr/local/cuda
> COPY --from=base /usr/include/cudnn.h /usr/include/cudnn.h
> COPY --from=base /usr/lib/x86_64-linux-gnu/libcudnn* /usr/lib/x86_64-linux-gnu/
> ```
> 
> From my understanding how multi staging works, this is not needed but I still copied the binaries while testing different setups. You are free to install Python directly to the CUDA image and drop the Python image.

from the runtime,i found the the files about cudnn is gone,but torch is can use gpu,and tensorflow is not,so i copy this file to the cuda dir,and generate an new image,it's work!

**Comment by skerdibash** [comment]
> Your gist does not work... same issue like I had:
> 
> ```
> #0 13.81 Setting up python3.10-minimal (3.10.12-1~22.04.2) ...
> #0 13.86 [Errno 13] Permission denied: '/usr/lib/python3.10/__pycache__/__future__.cpython-310.pyc.140307446897264'dpkg: error processing package python3.10-minimal (--configure):
> #0 13.86  installed python3.10-minimal package post-installation script subprocess returned error exit status 1
> #0 13.86 Errors were encountered while processing:
> #0 13.86  python3.10-minimal
> #0 13.87 E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

Did this error occure during the image building process, cause mine built successfully

**Comment by henryruhs** [comment]
@min-star please provide a complete Dockerfile

**Comment by min-star** [comment]
> @min-star please provide a complete Dockerfile
I use this base image nvidia/cuda:11.8.0-runtime-ubuntu22.04,and generated container,afterwards i docker exec  this container,setp by step install some environments,in the end, i copy the cudnn to the container and put it to the related cuda subdirs,so make a dockerfile need some time,i'll try it out.

**Comment by min-star** [comment]
> @min-star please provide a complete Dockerfile

first,i run the docker compose with your dockerfile,i found the container's cuda is gone,i think the python image overwrite something,and i use apt install python,the image is ok,the result is ok,i create a pull request,you can review!

**Comment by min-star** [comment]
![截图 2023-09-08 16-04-09](https://github.com/facefusion/facefusion-docker/assets/59134868/eb154351-47b8-47dd-96a4-bcaba1da60e7)

**Comment by min-star** [comment]
the torch and tensorflow cuda test
![image (8)](https://github.com/facefusion/facefusion-docker/assets/59134868/69bf1812-8354-4d47-862e-01fad4bd24c9)


the docker-compose.cuda.yml,i modify something yet.add privileged: true and the execute name modifed with python3.
![截图 2023-09-08 16-36-39](https://github.com/facefusion/facefusion-docker/assets/59134868/f0893ef2-fb8b-47a8-b3ed-3372e23692e4)

**Comment by henryruhs** [comment]
Tested your Dockerfile - does not work.

**Comment by min-star** [comment]
> Tested your Dockerfile - does not work.

did you modify the docker-compose.cuda.yml,add the privileged: true

**Comment by henryruhs** [comment]
yes... but that actual does not matter, when the build fails :-)

I'm under Ubuntu... should not matter but [skerdibash](https://github.com/skerdibash) said it works for him?

**Comment by henryruhs** [comment]
Works for me now, even without `privileged: true`. Thanks for everyone being envolved to fix it!

**Comment by min-star** [comment]
Congratulations,wish to contribute for open source,^_^!
