### ISSUE TITLE
Unable to start Facefusion docker - Error response from daemon: could not select device driver "rocm" with capabilities: [[gpu video]] - AMD Radeon RX 7900 XTX

### ISSUE THREAD

**Issue by arunhk3** [facefusion/facefusion-docker#31]
Hi,

I am using RX 7900 XTX and tried to run Facefusion using the steps provided but I ended up with the below error:

```
sudo docker compose -f docker-compose.rocm.yml up

Attaching to facefusion-rocm-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: could not select device driver "rocm" with capabilities: [[gpu video]]
```
I am unable to get past this error and could not find anything on the internet to solve the same.

Any help would be much appreciated.

Thanks!

**Comment by henryruhs** [comment]
Install ROCM...

**Comment by arunhk3** [comment]
I did have ROCM installed. I have ComfyUI and Stable Diffusion Webui working perfectly!

**Comment by henryruhs** [comment]
Good for you, GitHub is still not a support forum.
