### ISSUE TITLE
latest must cuda>=12.6 ?

### ISSUE THREAD

**Issue by chaoqunxie** [facefusion/facefusion-docker#36]
[+] Running 1/2
✔ Network facefusion-docker_default Created 0.1s
⠸ Container facefusion-docker-facefusion-cuda-1 Starting 0.3s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=12.6, please update your driver to a newer version, or use an earlier cuda container: unknown

**Comment by chaoqunxie** [comment]
![image](https://github.com/user-attachments/assets/475a6383-cb59-4802-a70d-b81ac3496d79)

**Comment by henryruhs** [comment]
send a PR with cuda 12.4 then.

**Comment by chaoqunxie** [comment]
> send a PR with cuda 12.4 then.

cat Dockerfile.cuda 
FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

ARG FACEFUSION_VERSION=3.0.0
ENV GRADIO_SERVER_NAME=0.0.0.0


WORKDIR /facefusion

RUN apt-get update
RUN apt-get install python3.10 -y
RUN apt-get install python-is-python3 -y
RUN apt-get install pip -y
RUN apt-get install git -y
RUN apt-get install curl -y
RUN apt-get install ffmpeg -y

RUN git clone https://github.com/facefusion/facefusion.git --branch ${FACEFUSION_VERSION} --single-branch .

RUN python install.py --onnxruntime cuda --skip-conda

i resove it

**Comment by henryruhs** [comment]
That is not actual a PR (pull request) but I quickly updated the CUDA and TensorRT Dockerfiles.

Please test if both are working, I just have too much on my hands to spin it up.
