### ISSUE TITLE
exited with code 139

### ISSUE THREAD

**Issue by RickySupriyadi** [facefusion/facefusion-docker#37]
how to replicate:
1. sudo docker compose -f docker-compose.cuda.yml up
2. it run
3. input sample image
4. docker container exited with code 139

machine:
kubuntu 24.04
GTX 1060 3GB, 128GB DD3, 2xE2690v2

have docker:
`docker --version
Docker version 27.3.1, build ce12230
`
did isntalled nvidia-container-toolkit --version:
`nvidia-container-toolkit --version
NVIDIA Container Runtime Hook version 1.16.2
`
did configured nvidia-ctk:
`sudo nvidia-ctk runtime configure --runtime=docker
cat /etc/docker/daemon.json
{
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
`

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
